development:
  adapter: postgresql
  encoding: unicode
  database: euler6_development
  pool: 5
  username: baranov
  password:

test:
  adapter: sqlite3
  database: db/test_db.sqlite3
  pool: 5
  timeout: 5000
