development:
 adapter: mysql2
 database: euler6_development
 encoding: utf8
 pool: 5
 min_messages: warning
 timeout: 5000
 username: root
 password:
 socket: /var/run/mysqld/mysqld.sock

test:
  adapter: sqlite3
  database: db/test_db.sqlite3
  pool: 5
  timeout: 5000
